name: kgcn_federated
channels:
  - rdkit
dependencies:
  - python=3.7.9
  - pip
  - rdkit=2020.03.3.0
  - pip:
    - tensorflow==2.3
    - joblib==0.17.0
    - wget==3.2
    - pandas==1.1.3
    - tensorflow_federated
